### ISSUE TITLE
JSON top level array cause shot dump

### ISSUE THREAD

**Issue by MaBecker** [fidley/JSON2ABAPType#10]
Hi,

you have done great work, many thank's for sharing!

Just tested some  JSON 
 
this works perfekt:

```
{
"name":"John",
"age":30,
"cars":[ "Ford", "BMW", "Fiat" ]
}
```

and this cause a dump

```
[{
"name":"John",
"age":30,
"cars":[ "Ford", "BMW", "Fiat" ]
}]
```

Any idea about this?

**Comment by fidley** [comment]
Thanks!

For the dump I'd need to check, but isn't this standard that JSON must
start with { ?

Cheers
Łukasz

W dniu czw., 30.01.2020 o 19:10 Mark Becker <notifications@github.com>
napisał(a):

**Comment by MaBecker** [comment]
Well, this is what I thought too.

It is a valid JSON and ABAP /ui2/cl_json can handle it.

[sample code](https://gist.github.com/MaBecker/9aab9d75294d8285f3ba928e5b9d1c5d)

**Comment by fidley** [comment]
![image](https://user-images.githubusercontent.com/7912195/74434624-150b1c80-4e63-11ea-9597-07f0e65bcaf1.png)

Should be solved now

**Comment by fidley** [comment]
please try it by yourself, then we will close the issue.

**Comment by MaBecker** [comment]
Just tested, works - Thanks 

![Bildschirmfoto 2020-02-13 um 21 14 54](https://user-images.githubusercontent.com/15932646/74474549-08f47e80-4ea6-11ea-81c6-42cdaa32d3ad.jpg)
