### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andkopp** [fidley/JSON2ABAPType#3]
Hi Lukasz.

Would it be possible to change the license of your project to Apache 2.0 or MIT? They are less restrictive and less risky to use for companies. Here is some information on the differences between the licenses: https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/

Best regards
Andreas

**Comment by fidley** [comment]
Hi Andreas,

done.

Cheers
Łukasz
